
require:
  - rubocop-rails


AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  SuggestExtensions: false
  CacheRootDirectory: ./tmp/rubocop/
  Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'db/**/*'
    - 'node_modules/**/*'
    - 'config/**/*'
    - 'app/channels/**/*'

Metrics/BlockLength:
  IgnoredMethods: ['describe', 'context', 'feature', 'scenario', 'let', 'it']
  Exclude: 
    - 'config/environments/**/*'

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Rails/HttpStatus:
  EnforcedStyle: numeric